Insert into DOLGOZO (DKOD,DNEV,FOGLALKOZAS,FONOKE,BELEPES,FIZETES,JUTALEK,OAZON) values ('1','D1','PRESIDENT',null,null,'3900',null,null);
Insert into DOLGOZO (DKOD,DNEV,FOGLALKOZAS,FONOKE,BELEPES,FIZETES,JUTALEK,OAZON) values ('2','D2','WHATEVER',null,null,'2000',null,null);
Insert into DOLGOZO (DKOD,DNEV,FOGLALKOZAS,FONOKE,BELEPES,FIZETES,JUTALEK,OAZON) values ('3','D3','FOO',null,null,'2000',null,null);
